name = "california-shutters-preview"

main = "src/index.js"
compatibility_date = "2024-11-04"


[[d1_databases]]
binding = "DB"
database_name = "california-shutters"
database_id = "4974f4f5-6e28-4850-b3ab-f4f9931b6d96"